#!/usr/bin/env bash

echo "[Config] Changing your shell to zsh ..."
  chsh -s $(which zsh)

echo "[Install] Homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  brew update

echo "[Install] Git"
  brew install git

echo "[Install] Postgres"
  brew install postgres --no-python
  initdb /usr/local/var/postgres

echo "[Install] Ack"
  brew install ack

echo "[Install] tmate"
  brew tap nviennot/tmate
  brew install tmate
  
echo "[Install] vim"
  brew install vim

echo "[Install] ImageMagick"
  brew install imagemagick --disable-openmp

echo "[Install] Ctags" # used by sublime
  brew install ctags

echo "[Install] vundle"
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  cp .vimrc ~/.vimrc

echo "[Install] Run Extra Scripts"
echo "bash <(curl -s https://raw.github.com/thatrubylove/macsetup/master/ruby)"
echo "bash <(curl -s https://raw.github.com/thatrubylove/macsetup/master/software)"

echo "[Install] dotfiles"
  git clone 'http://github.com/thatrubylove/dotfiles' ~/.dotfiles && cd ~/.dotfiles && rake install
